/**
 * actualizar_orden_catalogo.js
 * Actualiza el campo 'orden' en Firestore catalogo_web segun el TXT.
 * cd functions && node actualizar_orden_catalogo.js
 */
const admin = require('firebase-admin');
const path  = require('path');

const EID   = '0PoomHYDUJf5w8tDFRLhFi9iURF3';
const saPath = path.join(__dirname, 'serviceAccountKey.json');
admin.initializeApp({ credential: admin.credential.cert(require(saPath)) });
const db  = admin.firestore();
const col = db.collection('empresas').doc(EID).collection('catalogo_web');

// Orden deseado (título → posición)
const ORDEN = {
  "discurrir a proposito de": 1,
  "al son de la nostalgia": 2,
  "fe": 3,
  "el jardin de la memoria": 4,
  "entre lo pensado y lo vivido": 5,
  "la muerte como pretexto": 6,
  "el jardin de irene": 7,
  "manana nos vamos a paris": 8,
  "la ultima disidente": 9,
  "el mundial que espana no gano": 10,
  "espejos": 11,
  "premio volantones 2026": 12,
  "intramuros": 13,
  "novias del sepulcro": 14,
  "el monte de las animas y otras leyendas": 15,
  "morir no es irse a ningun sitio": 16,
  "johatsu y otros cuentos": 17,
  "la habitacion 320": 18,
  "el canto triste del cuervo": 19,
  "tu y el amor": 20,
  "destilacion": 21,
  "las doce cosechas": 22,
  "los rios nunca miran atras": 23,
  "la gestion del silencio": 24,
  "turismo ruralidad y crisis rural": 25,
  "cronica de un profesor de instituto": 26,
  "creo que te quiero": 27,
  "al tercer dia": 28,
  "lagrimaciendo sobre el vacio": 29,
  "orgia del silencio": 30,
  "el vacio huele a tabaco y serrin": 31,
  "casa madre": 32,
  "maneras de estar tumbada": 33,
  "nostalgias": 34,
  "trampantojos": 35,
  "en realidad no sentir": 36,
  "las tres vidas de benjamin cazenave": 37,
  "el cielo tras mis pasos": 38,
  "que soy la vida": 39,
  "premio volantones 2025": 40,
  "el tablero de ajedrez": 41,
  "el nino que hallo la felicidad rodeado de palabras": 42,
  "la vieja inquietud del aire": 43,
  "asi me converti en puta": 44,
  "caminando con tus ojos": 45,
  "eva de ur": 46,
  "noviembre": 47,
  "espacios naturales con historia": 48,
  "azogues": 49,
  "norberto y el tesoro": 50,
  "comodamente adormecido": 51,
  "ritmos del desierto": 52,
  "agridulce": 53,
  "las flores estan mal": 54,
  "curso de latin para principiantes": 55,
  "volver a granada": 56,
  "la noche de los cuentos anonimos": 57,
  "con brevedad y alevosia": 58,
  "cuando termina la ciencia y empieza la ficcion": 59,
  "la quinta en verde": 60,
  "donde esta la nueva recompensa": 61,
  "sin saber escribirme": 62,
  "entre pegas y apegos apuesta por ti": 63,
  "sinfonia criminal": 64,
  "el viaje": 65,
  "levedad de la sonrisa": 66,
  "la novena": 67,
  "el hombre absurdo": 68,
  "cuentame una tonteria": 69,
  "norberto rompe algo": 70,
  "ciudades y tierras salvajes de andalucia": 71,
  "la retorica del silencio": 72,
  "jonas y la esperanza": 73,
  "preludio muerte y fuga": 74,
  "buenos vientos": 75,
  "venganza la leyenda del fenix iv": 76,
  "el pedestal de los cobardes": 77,
  "por la vida rapida": 78,
  "la historia oculta del temple": 79,
  "numen": 80,
  "en el perfil del sueno": 81,
  "trilce imaginado": 82,
  "mi vida en el bunker": 83,
  "el organo y otros cuentos de navidad del s xxi": 84,
  "excerpta": 85,
  "el lugar de la caracola": 86,
  "skrdat iii al borde de la muerte": 87,
  "la corona del cuervo": 88,
  "la negra del prostibulo y otros poemas": 89,
  "el guardian de las rosas": 90,
  "el sofa de carmen": 91,
  "relatos fulgurantes": 92,
  "ritos de paso": 93,
  "la isla invertida": 94,
  "derrubios del vacio": 95,
  "el norte": 96,
  "en las cavernas del alma": 97,
  "coloquio de lo inefable": 98,
  "are lo que pude": 99,
  "los veranos que fuimos": 100,
  "lejos de toda esa gente con ideas": 101,
  "la primera persona alonso quijano autor del quijote": 102,
  "norberto y el regalo": 103,
  "amversos": 104,
  "oscuridad la leyenda del fenix iii": 105,
  "versos de arena": 106,
  "nada en la vida es isla": 107,
  "yo tampoco me llamo ulises": 108,
  "frente a la voz del mundo": 109,
  "la verdad sea dicha y otras mentiras verdaderas": 110,
  "escarabajos": 111,
  "en voz baja": 112,
  "nostalgia del cielo": 113,
  "el tocadiscos de tito": 114,
  "la silla del moro": 115,
  "gritos de silencio": 116,
  "el espiritu del maristan nazari": 117,
  "el jardin de estocolmo": 118,
  "ladrar a la luna": 119,
  "sin proposito de enmienda": 120,
  "el arbol azul": 121,
  "la herencia de cain iii": 122,
  "transgresion": 123,
  "muerte en el consistorio": 124,
  "de juzgados y sombras": 125,
  "en la piel del tiempo": 126,
  "oximoron": 127,
  "jueves": 128,
  "el dia y todas las cosas me esperan": 129,
  "la cuarentena de los necios": 130,
  "la bruma que apacigua la memoria": 131,
  "la herencia de cain ii": 132,
  "el intercambio": 133,
  "crisis humanitaria": 134,
  "el blues de ogawa": 135,
  "camino sin senalizar": 136,
  "desabrochar la piel": 137,
  "somnium": 138,
  "poesia completa de enrique moron": 139,
  "los castillos templarios de espana": 140,
  "azul klein": 141,
  "una casa en el albaicin": 142,
  "el grito de los arboles": 143,
  "la pasion en prosa": 144,
  "huyendo a granada": 145,
  "la herencia de cain i": 146,
  "eres lo que escuchas": 147,
  "los 101 vericuetos de marrakech": 148,
  "el maristan nazari y sus hukama": 149,
  "acordes de tormenta y cielo": 150,
  "cuerpos de agua mujeres de luz": 151,
  "skrdat ii": 152,
  "ubicuo alud de nivea luz divina": 153,
  "huella liquida": 154,
  "el diccionario del alma": 155,
  "el repliegue de los espejos": 156,
  "huerto sagrado": 157,
  "el campo de alfalfa": 158,
  "la mirada del frio": 159,
  "cautivos en libertad": 160,
  "la nina que estuvo": 161,
  "origen la leyenda del fenix ii": 162,
  "huellas en la nieve": 163,
  "poker de ases": 164,
  "el secreto del castillo maldito": 165,
  "las leyes de kirchhoff": 166,
  "coloquios con arturo": 167,
  "desde alandalus": 168,
  "skrdat i": 169,
  "el holocausto cataro": 170,
  "teatro de alarma": 171,
  "amor eterno": 172,
  "ella y el faro": 173,
  "el toque de las animas": 174,
  "regreso al valle del olvido": 175,
  "asedio al maristan nazari": 176,
  "presencias y ausencias": 177,
  "donde termina la lluvia": 178,
  "el enigma de abravanel": 179,
  "hego": 180,
  "sonetario": 181,
  "el hombre analogico": 182,
  "el circulo de aton": 183,
  "porno para miopes joan marquez franch": 184,
  "la distancia encendida": 185,
  "rilkowktramas trim": 186,
  "inventario del tiempo": 187,
  "sembrando color": 188,
  "gastronomia y poesia en la alpujarra": 189,
  "sobre la nostalgia y el olvido": 190,
  "un ario andalusi en persia": 191,
  "fria aritmetica": 192,
  "sit tibi terra levis iii de aurorae diebus lorenzo algar molinos": 193,
  "opium": 194,
  "temporada de granadas": 195,
  "bombon midnight cravings": 196,
  "el oido del viento": 197,
  "cazulas": 198,
  "la memoria del expreso": 199,
  "el estupor de los atlantes": 200,
  "elegias": 201,
  "el centinela impaciente": 202,
  "sit tibi terra levis ii de spei diebus": 203,
  "preocupaciones": 204,
  "la leyenda del fenix": 205,
  "el camino de vuelta a casa": 206,
  "la oscuridad volvio a quedarse quieta": 207,
  "laberinto": 208,
  "el puente": 209,
  "tres sinfonias": 210,
  "refutacion del efecto doppler": 211,
  "deconstrucciones": 212,
  "la noche de los cascabeles alex marin canals": 213,
  "ellas y ellos cuentos de familia": 214,
  "sit tibi terra levis de laetitiae diebus": 215,
  "chinas en los zapatos": 216,
  "ciber evolucion corrupcion en la ciudad tecnologica": 217,
  "el gran poeta esta rezando": 218,
  "igor el ogro": 219,
  "libro de las imaginaciones": 220,
  "x": 221,
  "ojos claros para dias oscuros": 222,
  "el caso solipandi": 223,
  "lo que cuesta nacer": 224,
  "pabellon d": 225,
  "ultima": 226,
  "sombra de un animal bebiendo sombra": 227,
  "lo que ocultan sus miradas": 228,
  "estancias a lo incierto": 229,
  "hudson": 230,
  "los heroes estan lejos": 231,
  "arponera cafe": 232,
  "coaccion": 233,
  "la noche de walpurgis": 234,
  "ni un dia sin una linea": 235,
  "tempo": 236,
  "palabra iluminada": 237,
  "un verano en la montana": 238,
  "decepciones": 239,
  "vertedero clausurado": 240,
  "crepusculo eviterno y elegias de anoranza": 241,
  "cementerio de medicos": 242,
  "yo la tierra que ahora piso": 243,
  "el mecanismo": 244,
  "hotel penumbra": 245,
  "el naufrago afortunado": 246,
  "lagrima roja": 247,
  "imperutopicoposibles": 248,
  "no somos flores": 249,
  "la isla cerrada": 250,
  "barminan las hogueras del inquisidor lucero": 251,
  "tiempos de honor": 252,
  "sales a jugar un ratito": 253,
  "lorca luces y sombras": 254,
  "los suenos del naufrago": 255,
  "la distancia trazada entre dos cuerpos": 256,
  "angulos": 257,
  "la piel de la intemperie": 258,
  "al abrigo del frio": 259,
  "el alba inacabada": 260,
  "para ir conociendo nuestras plantas mas cercanas": 261,
  "el ruido que haces al vivir": 262,
  "gotas de doble filo": 263,
  "como pudiste hacerme esto a mi": 264,
  "segundas oportunidades": 265,
  "teatro de sombras": 266,
  "memorial shadow pilar quirosacheyrouze": 267,
  "mientras las limusinas esperan en la calle": 268,
  "el verano ya no esta aqui": 269,
  "voces de madrugada": 270,
  "los papeles de juan espanol i la mano quemada": 271,
  "reconexion": 272,
  "mil formas de decir la palabra universo": 273,
  "imposibles impensables": 274,
  "nocturnario": 275,
  "la caja de pandora": 276,
  "rapsodia en negro y rojo": 277,
  "los conciertos": 278,
  "trilogia poetica de un hombre silente": 279,
  "el recuerdo nunca duerme": 280,
  "luciernagas": 281,
  "los trigos tan azules": 282,
  "monodialogos frente al espejo": 283,
  "ultima batalla el senor de las bestias": 284,
  "algo mas que palabras": 285,
  "camino a puerto hermoso": 286,
  "nos": 287,
  "la luz del fin de la tierra": 288,
  "el creador de animas": 289,
  "el ultimo vuelo del microraptor": 290,
  "hormonautas": 291,
  "suenos dispersos": 292,
  "alianzas": 293,
  "33 suenos": 294,
  "los anos sesenta en granada y el centro eicu fundado por d javier galindo blas": 295,
  "donde lloran los dragones": 296,
  "antagonia": 297,
  "los dias que me debes": 298,
  "no sin mi pueblo": 299,
  "y tu cuando mueres la historia de lidia": 300,
  "exiliados": 301,
  "poesia con perdon luis lopezquinones ruiz": 302,
  "sulayr dame cobijo": 303,
  "el alma del tonel": 304,
  "taifar pedro ruizcabello fernandez": 305,
  "relatos de una luna muerta": 306,
  "despertando a la vida que mejor regalo que la felicidad": 307,
  "versos de una crisis": 308,
  "ashaverus el libidinoso": 309,
  "la corriente de groenlandia": 310,
  "la vida es una palabra muy corta": 311,
  "hilvanes del agua": 312,
  "tiempo gris de cosmos": 313,
  "el legado de los dioses iii el ultimo angel": 314,
  "garbine": 315,
  "el corazon del roble": 316,
  "asesinato en la alhambra": 317,
  "art mariage los estados del alma": 318,
  "desde el puerto de la utopia": 319,
  "alejado del tiempo": 320,
  "el viento en tu cara": 321,
  "nocturnos": 322,
  "cautivo": 323,
  "asoka": 324,
  "ukigumo": 325,
  "de mal en peor": 326,
  "la fatalidad": 327,
  "la dadiva escondida en la palabra": 328,
  "la catedral de los suenos": 329,
  "nunca es tarde": 330,
  "gimena el sueno de una tortuga": 331,
  "el falsificador de la alcazaba": 332,
  "el relampago en la habitacion": 333,
  "el legado de los dioses ii": 334,
  "nadie me esperaba": 335,
  "mentre cambi sono con te": 336,
  "maldito vicio": 337,
  "cuentos de otro mundo": 338,
  "el legado de los dioses i": 339
};

function normStr(s) {
  return (s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'')
    .toLowerCase().replace(/[^\w\s]/g,'').replace(/\s+/g,' ').trim();
}

async function main() {
  const snap = await col.get();
  let batch = db.batch(), cnt = 0, actualiz = 0;
  snap.docs.forEach(doc => {
    const d     = doc.data();
    const titulo = d.titulo || d.nombre || '';
    const n      = normStr(titulo);
    // Buscar posición por exacto o parcial
    let pos = ORDEN[n];
    if (!pos) {
      for (const [k, v] of Object.entries(ORDEN)) {
        if ((k.startsWith(n) || n.startsWith(k)) && Math.abs(k.length-n.length) < 20) {
          pos = v; break;
        }
      }
    }
    if (pos) {
      batch.update(doc.ref, { orden: pos });
      actualiz++;  cnt++;
      if (cnt >= 400) { batch.commit(); batch = db.batch(); cnt = 0; }
    }
  });
  if (cnt > 0) await batch.commit();
  console.log('✅ Actualizado orden en ' + actualiz + ' libros de catalogo_web');
  process.exit(0);
}
main().catch(e => { console.error(e); process.exit(1); });
