/**
 * importar_nazari_data.js
 * Script de importación única: sube todos los eventos, noticias y entrevistas
 * de la web estática de Editorial Nazarí a Firestore.
 *
 * Uso:
 *   cd functions
 *   node importar_nazari_data.js
 *
 * Requiere: firebase-admin (ya instalado en functions/)
 * Credenciales: usa GOOGLE_APPLICATION_CREDENTIALS o Application Default Credentials
 * (ejecutar antes: firebase login && firebase use planeaapp-4bea4)
 */

const admin = require('firebase-admin');
const fs    = require('fs');
const path  = require('path');
const os    = require('os');

// ── Credential: Firebase CLI stored refresh token ─────────────────────────────
function getRefreshToken() {
  const candidates = [
    path.join(os.homedir(), '.config', 'configstore', 'firebase-tools.json'),
    path.join(process.env.APPDATA || '', 'Roaming', 'configstore', 'firebase-tools.json'),
    path.join(process.env.APPDATA || '', 'configstore', 'firebase-tools.json'),
  ];
  for (const p of candidates) {
    try {
      const d = JSON.parse(fs.readFileSync(p, 'utf8'));
      const rt = d?.tokens?.refresh_token;
      if (rt) return rt;
    } catch (_) {}
  }
  return null;
}

const refreshToken = getRefreshToken();
if (!refreshToken) {
  console.error('❌ No se encontró el token de Firebase CLI. Ejecuta "firebase login" primero.');
  process.exit(1);
}

admin.initializeApp({
  credential: admin.credential.refreshToken({
    type:          'authorized_user',
    client_id:     '563584335869-fgrhgmd47bqnekij5i8b5pr03ho849e6.apps.googleusercontent.com',
    client_secret: 'j9iVZfS8ywKVtZdp0to4vn1p',
    refresh_token: refreshToken,
  }),
  projectId: 'planeaapp-4bea4',
});

const db      = admin.firestore();
const EID     = '0PoomHYDUJf5w8tDFRLhFi9iURF3';
const colBase = db.collection('empresas').doc(EID);

// ── Helpers ───────────────────────────────────────────────────────────────────
function parseFecha(str) {
  // Acepta 'YYYY-MM-DD' o 'YYYY-MM-DDTHH:MM:SS...'
  const d = new Date(str + (str.length === 10 ? 'T12:00:00' : ''));
  return isNaN(d.getTime()) ? new Date() : d;
}

function tipoEventoLabel(raw) {
  const map = {
    'presentacion': 'Presentación',
    'presentación': 'Presentación',
    'presentacion': 'Presentación',
    'firma':        'Presentación', // la app trata Firma como Presentación (TipoEventoExt.fromId)
    'feria':        'Feria',
    'taller':       'Taller',
    'lectura':      'Lectura',
    'conferencia':  'Evento',
    'premio':       'Evento',
  };
  if (!raw) return 'Presentación';
  return map[raw.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g,'')]
      || raw; // ya viene capitalizado
}

async function uploadBatch(colRef, docs, label) {
  let batch = db.batch();
  let count = 0;
  let total = 0;
  for (const [id, data] of docs) {
    batch.set(colRef.doc(id), data, { merge: true });
    count++;
    total++;
    if (count === 400) { // máx 500 por batch; usamos 400 para margen
      await batch.commit();
      batch = db.batch();
      count = 0;
      process.stdout.write(`  ${label}: ${total} subidos...\r`);
    }
  }
  if (count > 0) await batch.commit();
  console.log(`  ✅ ${label}: ${total} documentos importados`);
}

// ─────────────────────────────────────────────────────────────────────────────
// DATOS — Eventos (extraídos de eventos-data.js)
// ─────────────────────────────────────────────────────────────────────────────
const EVENTOS_RAW = [
  { id: 'ev-001', tipo: 'Firma',         titulo: "'El canto triste del cuervo' en la Feria del Libro de Jaén",       subtitulo: 'José Prados Osuna firma ejemplares',                                    fecha: '2026-05-16', hora: '18:30 – 20:25 h', lugar: 'Feria del Libro de Jaén, c/ Roldán y Marín', ciudad: 'Jaén',                    imagen: '', descripcion: 'José Prados Osuna firma ejemplares de su última novela El canto triste del cuervo en la Feria del Libro de Jaén.' },
  { id: 'ev-002', tipo: 'Presentación',  titulo: "'Intramuros' en Sevilla",                                          subtitulo: 'José Piñero Mira presenta su colección de relatos',                      fecha: '2026-05-16', hora: '20:30 – 22:00 h', lugar: 'Sala Griot, c/ Factores 18',                ciudad: 'Sevilla',                 imagen: '', descripcion: 'Presentación de Intramuros, colección de relatos de José Piñero Mira, acompañado por Alejandro Santiago y Xavi Rodríguez.' },
  { id: 'ev-003', tipo: 'Presentación',  titulo: "'Noviembre' en Salar",                                             subtitulo: 'Juan de Dios Villanueva Roa presenta su poemario',                       fecha: '2026-05-22', hora: '19:30 – 21:00 h', lugar: 'Salón de Plenos del Ayuntamiento de Salar',  ciudad: 'Salar (Granada)',         imagen: '', descripcion: 'Presentación de Noviembre, último poemario de Juan de Dios Villanueva Roa, con recitación de Sandra Rodríguez y acompañamiento musical.' },
  { id: 'ev-004', tipo: 'Presentación',  titulo: "'Las doce cosechas' en Algeciras",                                 subtitulo: 'Maite Cuesta presenta su nueva novela',                                 fecha: '2026-05-22', hora: '20:00 – 21:30 h', lugar: 'Casa Regional de Ceuta en Algeciras, c/ José Luis Cano 1', ciudad: 'Algeciras (Cádiz)', imagen: '', descripcion: 'Presentación de Las doce cosechas, nueva novela de Maite Cuesta, acompañada por la escritora Alicia Morales.' },
  { id: 'ev-005', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en Atarfe",                               subtitulo: 'Irene Bosch Blanco presenta su primera novela',                          fecha: '2026-05-27', hora: '19:30 – 21:00 h', lugar: 'Centro Cultural Medina Elvira, Avda. de la Diputación S/N', ciudad: 'Atarfe (Granada)', imagen: '', descripcion: 'Presentación de Caminando con tus ojos, la ópera prima de Irene Bosch Blanco, en el Centro Cultural Medina Elvira de Atarfe.' },
  { id: 'ev-006', tipo: 'Presentación',  titulo: "'La gestión del silencio' en Gijón",                               subtitulo: 'Manuel Bayona presenta sus artículos sobre gestión sanitaria',            fecha: '2026-05-28', hora: '19:00 – 20:30 h', lugar: 'Salón de actos de la Escuela de Comercio, c/ Francisco Tomás y Valiente 1', ciudad: 'Gijón (Asturias)',   imagen: '', descripcion: 'Presentación de La gestión del silencio de Manuel Bayona, con la presencia de la alcaldesa de Gijón y la consejera de Salud.' },
  { id: 'ev-007', tipo: 'Firma',         titulo: "'Creo que te quiero' en la Feria del Libro de Pegalajar",          subtitulo: 'Dulce López Rodríguez firma ejemplares',                                fecha: '2026-05-30', hora: '11:00 – 14:00 y 16:00 – 19:30 h', lugar: 'Feria del Libro de Pegalajar, Parque de La Charca', ciudad: 'Pegalajar (Jaén)', imagen: '', descripcion: 'Dulce López Rodríguez firma ejemplares de Creo que te quiero en la Feria del Libro de Pegalajar.' },
  { id: 'ev-008', tipo: 'Presentación',  titulo: "'La habitación 320' en Barcelona",                                 subtitulo: 'El Grupo Bojador presenta su colección de relatos',                      fecha: '2026-05-31', hora: '12:00 – 14:00 h', lugar: 'Café de la Ópera, La Rambla 74',             ciudad: 'Barcelona',               imagen: '', descripcion: 'El Grupo Bojador (Ana Moya, Ángel Elgue, Jordi Isern, María Eugenia Oliver y Marimén Ayuso) presenta La habitación 320.' },
  { id: 'ev-009', tipo: 'Presentación',  titulo: "'La gestión del silencio' en Oviedo",                              subtitulo: 'Manuel Bayona en el Aula Clarín de la Universidad de Oviedo',            fecha: '2026-06-01', hora: '19:00 – 20:30 h', lugar: 'Aula Clarín, edificio histórico Universidad, c/ San Francisco', ciudad: 'Oviedo (Asturias)', imagen: '', descripcion: 'Presentación de La gestión del silencio de Manuel Bayona en el Aula Clarín de la Universidad de Oviedo.' },
  { id: 'ev-010', tipo: 'Presentación',  titulo: "'La gestión del silencio' en Madrid",                              subtitulo: 'Manuel Bayona ante directivos del Ministerio de Sanidad',                fecha: '2026-06-09', hora: '13:00 – 14:30 h', lugar: 'Plató de TV de Redacción Médica, c/ Rufino González 23 BIS', ciudad: 'Madrid',            imagen: '', descripcion: 'Presentación de La gestión del silencio con la presencia del Director General de Ordenación Profesional del Ministerio de Sanidad.' },
  { id: 'ev-011', tipo: 'Presentación',  titulo: "'Espejos' en Madrid",                                              subtitulo: 'Óscar Vázquez Mínguez presenta su poemario de 52 poemas',                fecha: '2026-06-09', hora: '19:00 – 20:30 h', lugar: 'Biblioteca Pública Municipal Manuel Vázquez Montalbán, c/ Francos Rodríguez 67', ciudad: 'Madrid', imagen: '', descripcion: 'Óscar Vázquez Mínguez presenta Espejos, acompañado por la escritora Carolina Illescas y el editor Alejandro Santiago.' },
  { id: 'ev-012', tipo: 'Premio',        titulo: "Premio Volantones 2026 de Microrrelatos en Granada",               subtitulo: 'Concesión del premio organizado por la Asociación de Amigos de la Base Aérea de Armilla', fecha: '2026-06-05', hora: '19:00 – 20:30 h', lugar: 'Sala Val del Omar, Biblioteca de Andalucía, c/ Profesor Sainz Cantero 6', ciudad: 'Granada', imagen: '', descripcion: 'Presentación del Premio Volantones 2026 de Microrrelatos y concesión del galardón al ganador.' },
  { id: 'ev-013', tipo: 'Firma',         titulo: "'Trampantojos' en la Feria del Libro de Madrid",                   subtitulo: 'Ana Grandal firma su colección de 75 microrrelatos',                     fecha: '2026-06-10', hora: '17:30 – 18:00 h', lugar: 'Caseta 170 de Sin Tarima Libros, Feria del Libro de Madrid', ciudad: 'Madrid',          imagen: '', descripcion: 'Ana Grandal firma ejemplares de Trampantojos, una colección de 75 microrrelatos, en la Feria del Libro de Madrid.' },
  { id: 'ev-014', tipo: 'Presentación',  titulo: "'Destilación' en Granada",                                         subtitulo: 'Paula R. Bouzas presenta su poemario en el Colegio de Farmacéuticos',   fecha: '2026-06-17', hora: '20:00 – 21:30 h', lugar: 'Colegio Oficial de Farmacéuticos de Granada, c/ San Jerónimo 16', ciudad: 'Granada',          imagen: '', descripcion: 'Presentación de Destilación, poemario de Paula R. Bouzas, con la presencia de la Decana de la Facultad de Farmacia de la UGR.' },
  { id: 'ev-015', tipo: 'Presentación',  titulo: "'Al tercer día' en Isla Cristina",                                 subtitulo: 'David Macías Gómez presenta su novela histórica',                        fecha: '2026-07-13', hora: '21:00 – 22:30 h', lugar: 'CIT Garum, Muelle Marina S/N',               ciudad: 'Isla Cristina (Huelva)', imagen: '', descripcion: 'Presentación de Al tercer día, nueva novela de David Macías Gómez.' },
  { id: 'ev-016', tipo: 'Conferencia',   titulo: "Conferencia «Cátaros en el Pirineo catalán»",                      subtitulo: 'Jesús Ávila Granados, autor de El holocausto cátaro',                    fecha: '2026-08-08', hora: '18:00 – 19:30 h', lugar: "Casals de Jubilats de Tírvia, Carrer de la Plaça de la Monja 1", ciudad: "Tírvia (Lleida)",  imagen: '', descripcion: "Conferencia «Cátaros en el Pirineo catalán» a cargo de Jesús Ávila Granados." },
  { id: 'ev-017', tipo: 'Presentación',  titulo: "'Al tercer día' en la Feria del Libro de Alájar",                 subtitulo: 'David Macías Gómez presenta su novela histórica',                        fecha: '2026-08-12', hora: '20:00 – 21:30 h', lugar: "Biblioteca Pública Municipal «Arias Montano» (Centro Multifuncional)", ciudad: 'Alájar (Huelva)', imagen: '', descripcion: 'Presentación de Al tercer día de David Macías Gómez en la Feria del Libro de Alájar.' },
  { id: 'ev-018', tipo: 'Presentación',  titulo: "'La gestión del silencio' en Candás",                              subtitulo: 'Manuel Bayona presenta su obra sobre gestión sanitaria',                  fecha: '2026-09-17', hora: '19:00 – 20:30 h', lugar: "Biblioteca Pública Municipal «Carlos González Posada», Sala Benito d'Auxa, c/ Enrique Alau Flores 1", ciudad: 'Candás (Asturias)', imagen: '', descripcion: 'Presentación de La gestión del silencio de Manuel Bayona en Candás.', autor_nombre: 'Manuel Bayona García' },
  { id: 'ev-019', tipo: 'Presentación',  titulo: "'Destilación' en Ribadavia",                                       subtitulo: 'Paula R. Bouzas presenta su poemario en Ribadavia',                      fecha: '2026-08-14', hora: '', lugar: 'Ribadavia',                                               ciudad: 'Ribadavia (Ourense)',      imagen: '', descripcion: "Presentación de Destilación, poemario de Paula R. Bouzas, en Ribadavia." },
  { id: 'ev-020', tipo: 'Presentación',  titulo: "'El mundial que España no ganó' en Torrelavega",                   subtitulo: 'Presentación en Torrelavega',                                            fecha: '2026-08-14', hora: '', lugar: 'Torrelavega',                                              ciudad: 'Torrelavega (Cantabria)',  imagen: '', descripcion: "Presentación de El mundial que España no ganó en Torrelavega." },
  { id: 'ev-021', tipo: 'Presentación',  titulo: "'El mundial que España no ganó' en Granada",                       subtitulo: 'Javier Ruiz Barquín presenta su diario íntimo',                          fecha: '2026-09-16', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: "Presentación de El mundial que España no ganó, diario íntimo de Javier Ruiz Barquín.", autor_nombre: 'Javier Ruiz Barquín' },
  { id: 'ev-022', tipo: 'Presentación',  titulo: "'La habitación 320' en Granada",                                   subtitulo: 'El Grupo Bojador presenta su colección de relatos en Granada',           fecha: '2026-09-24', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'El Grupo Bojador presenta La habitación 320 en Granada.' },
  { id: 'ev-023', tipo: 'Presentación',  titulo: "'El jardín de Irene' en Granada",                                  subtitulo: 'Presentación en el barrio de La Chana, Granada',                        fecha: '2026-10-23', hora: '', lugar: 'La Chana, Granada',                                         ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de El jardín de Irene en el barrio de La Chana de Granada.' },
  { id: 'ev-024', tipo: 'Presentación',  titulo: "'Mujeres y guerra' en Granada",                                    subtitulo: 'Presentación en Granada',                                               fecha: '2026-05-01', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación del libro Mujeres y guerra en Granada.' },
  { id: 'ev-025', tipo: 'Presentación',  titulo: "'Huyendo a Granada' — Ruta literaria",                             subtitulo: 'Ruta literaria por la ciudad de Granada',                               fecha: '2026-05-03', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Ruta literaria por los escenarios de Huyendo a Granada, con Victoria Eugenia Muñoz.' },
  { id: 'ev-026', tipo: 'Presentación',  titulo: "'Maneras de estar tumbada' en Granada",                            subtitulo: 'Presentación en Granada',                                               fecha: '2026-05-05', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación del libro de Mar Navarro G.' },
  { id: 'ev-027', tipo: 'Presentación',  titulo: "'Al tercer día' en Granada",                                       subtitulo: 'David Macías Gómez presenta su novela histórica',                        fecha: '2026-05-06', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de Al tercer día, novela histórica de David Macías Gómez, en Granada.' },
  { id: 'ev-028', tipo: 'Presentación',  titulo: "'Cómodamente adormecido' en Granada",                              subtitulo: 'Juan Quero presenta su novela',                                          fecha: '2026-05-10', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de Cómodamente adormecido de Juan Quero en Granada.' },
  { id: 'ev-029', tipo: 'Presentación',  titulo: "'Al tercer día' — segunda presentación",                           subtitulo: 'David Macías Gómez presenta su novela',                                 fecha: '2026-05-11', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Segunda presentación de Al tercer día de David Macías Gómez.' },
  { id: 'ev-030', tipo: 'Presentación',  titulo: "'Los ríos nunca miran atrás' en Granada",                          subtitulo: 'José Luis Monroy Antón presenta su novela',                             fecha: '2026-05-14', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de Los ríos nunca miran atrás en Granada.' },
  { id: 'ev-031', tipo: 'Presentación',  titulo: "'Nostalgias' en Granada",                                          subtitulo: 'Susana Collado Vázquez presenta su poemario',                           fecha: '2026-05-14', hora: '', lugar: 'Granada',                                                  ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación del poemario Nostalgias de Susana Collado Vázquez en Granada.' },
  { id: 'ev-032', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en el Café Literario de Atarfe",          subtitulo: 'Irene Bosch Blanco presenta su novela',                                 fecha: '2026-04-22', hora: '', lugar: 'Café Literario de Atarfe',                                 ciudad: 'Atarfe (Granada)',         imagen: '', descripcion: 'Encuentro con autores durante la semana del libro en Atarfe.' },
  { id: 'ev-033', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en La Ciutadella",                        subtitulo: 'Irene Bosch Blanco presenta su novela en Menorca',                       fecha: '2026-04-17', hora: '', lugar: 'Antigua farmacia Llabrés',                                 ciudad: 'Ciutadella (Menorca)',     imagen: '', descripcion: 'Irene Bosch Blanco presentó su novela en la antigua farmacia Llabrés de Ciutadella.' },
  { id: 'ev-034', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en Ferrerías",                            subtitulo: 'Presentación en la Biblioteca de Ferrerías',                            fecha: '2026-04-16', hora: '', lugar: 'Biblioteca Municipal de Ferrerías',                          ciudad: 'Ferrerías (Menorca)',      imagen: '', descripcion: 'Irene Bosch Blanco presentó su novela en la Biblioteca de Ferrerías.' },
  { id: 'ev-035', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en Es Migjorn Gran",                      subtitulo: 'Encuentro con el Club de Jubilados',                                     fecha: '2026-04-15', hora: '', lugar: 'Club de Jubilados',                                         ciudad: 'Es Migjorn Gran (Menorca)', imagen: '', descripcion: 'El Club de Jubilados de Es Migjorn Gran recibió a Irene Bosch Blanco para presentar su libro.' },
  { id: 'ev-036', tipo: 'Presentación',  titulo: "'Las doce cosechas' en Ceuta",                                     subtitulo: 'Maite Cuesta presenta su novela',                                        fecha: '2026-04-15', hora: '', lugar: 'Biblioteca Pública del Estado',                             ciudad: 'Ceuta',                   imagen: '', descripcion: 'Presentación de la novela de Maite Cuesta en la Biblioteca Pública del Estado en Ceuta.' },
  { id: 'ev-037', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en el CEIP Pere Casasnovas",              subtitulo: 'Taller literario para alumnos de primaria',                             fecha: '2026-04-14', hora: '', lugar: 'CEIP Pere Casasnovas',                                      ciudad: 'Ciutadella (Menorca)',     imagen: '', descripcion: 'Irene Bosch Blanco realizó un taller para alumnos de sexto de primaria.' },
  { id: 'ev-038', tipo: 'Presentación',  titulo: "'Tú y el amor' en Orihuela",                                       subtitulo: 'Jesús Paredes Ortiz presenta su poemario',                              fecha: '2026-04-13', hora: '', lugar: 'Biblioteca Pública Municipal María Moliner',                 ciudad: 'Orihuela (Alicante)',      imagen: '', descripcion: 'Presentación del poemario de Jesús Paredes Ortiz en la Biblioteca Pública Municipal María Moliner.' },
  { id: 'ev-039', tipo: 'Presentación',  titulo: "'El canto triste del cuervo' en Granada",                          subtitulo: 'José Prados Osuna presenta su novela histórica',                         fecha: '2026-04-10', hora: '', lugar: 'Biblioteca de Andalucía',                                   ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de la novela histórica de José Prados Osuna en la Biblioteca de Andalucía.' },
  { id: 'ev-040', tipo: 'Presentación',  titulo: "'La gestión del silencio' en Málaga",                              subtitulo: 'Manuel Bayona presenta su libro',                                        fecha: '2026-03-26', hora: '', lugar: 'Colegio Oficial de Médicos de Málaga',                       ciudad: 'Málaga',                  imagen: '', descripcion: 'Presentación del libro de Manuel Bayona con profesionales sanitarios en el Colegio Oficial de Médicos de Málaga.' },
  { id: 'ev-041', tipo: 'Presentación',  titulo: "'Lagrimaciendo sobre el vacío' en Íllora",                         subtitulo: 'Ana Barea Arco presenta su poemario',                                    fecha: '2026-04-10', hora: '', lugar: 'Biblioteca Pública Municipal',                              ciudad: 'Íllora (Granada)',         imagen: '', descripcion: 'Presentación del poemario de Ana Barea Arco en la Biblioteca Pública Municipal de Íllora.' },
  { id: 'ev-042', tipo: 'Presentación',  titulo: "'Destilación' en el Carmen de la Victoria (Granada)",              subtitulo: 'Paula R. Bouzas presenta su poemario',                                  fecha: '2026-03-27', hora: '', lugar: 'Carmen de la Victoria',                                    ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación en un espacio íntimo de Granada que acogió la voz de Paula R. Bouzas.' },
  { id: 'ev-043', tipo: 'Presentación',  titulo: "'La vieja inquietud del aire' en Córdoba",                         subtitulo: 'Diego Castillo Barco presenta su libro',                                fecha: '2026-03-21', hora: '', lugar: 'Biblioteca Pública Grupo Cántico',                           ciudad: 'Córdoba',                 imagen: '', descripcion: 'Presentación del libro de Diego Castillo Barco en la Biblioteca Pública Grupo Cántico de Córdoba.' },
  { id: 'ev-044', tipo: 'Presentación',  titulo: "'La gestión del silencio' en Huelma",                              subtitulo: 'Manuel Bayona presenta su libro',                                        fecha: '2026-03-20', hora: '', lugar: 'Huelma',                                                    ciudad: 'Huelma (Jaén)',           imagen: '', descripcion: 'Presentación de la obra de Manuel Bayona García.' },
  { id: 'ev-045', tipo: 'Presentación',  titulo: "'Las doce cosechas' en Granada",                                   subtitulo: 'Maite Cuesta presenta su novela',                                        fecha: '2026-03-25', hora: '', lugar: 'Biblioteca Pública Municipal Francisco Ayala',               ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de la nueva novela de Maite Cuesta en la Biblioteca Pública Municipal Francisco Ayala.' },
  { id: 'ev-046', tipo: 'Presentación',  titulo: "'Los ríos nunca miran atrás' en Jerte",                            subtitulo: 'José Luis Monroy Antón en el Festival Despierta 26',                     fecha: '2026-03-25', hora: '', lugar: 'Festival Despierta 26',                                     ciudad: 'Jerte (Cáceres)',          imagen: '', descripcion: 'Presentación de la obra de José Luis Monroy Antón en el Festival Literario Despierta 26.' },
  { id: 'ev-047', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en la ONCE (Granada)",                   subtitulo: 'Irene Bosch Blanco presenta su novela',                                 fecha: '2026-03-19', hora: '', lugar: 'Sede de la ONCE en Granada',                                ciudad: 'Granada',                 imagen: '', descripcion: 'Irene Bosch Blanco presentó su libro en la sede de la ONCE en Granada.' },
  { id: 'ev-048', tipo: 'Presentación',  titulo: "'Los ríos nunca miran atrás' en Granada",                          subtitulo: 'Presentación en el Cuarto Real de Santo Domingo',                       fecha: '2026-04-15', hora: '', lugar: 'Cuarto Real de Santo Domingo',                               ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de la novela de José Luis Monroy Antón en el Cuarto Real de Santo Domingo.' },
  { id: 'ev-049', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en La Cocina de Molinos",                subtitulo: 'Presentación en Granada',                                               fecha: '2026-03-12', hora: '', lugar: 'La Cocina de Molinos',                                      ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación del 12 de marzo en el corazón de Granada ante un público con conocimiento personal de la discapacidad.' },
  { id: 'ev-050', tipo: 'Presentación',  titulo: "'Caminando con tus ojos' en el CEIP La Inmaculada",               subtitulo: 'Taller con alumnos',                                                    fecha: '2026-03-09', hora: '', lugar: 'CEIP Ecoescuela La Inmaculada',                             ciudad: 'Granada',                 imagen: '', descripcion: 'Encuentro especial del 9 de marzo entre Irene Bosch y alumnos del colegio.' },
  { id: 'ev-051', tipo: 'Presentación',  titulo: "'La gestión del silencio' en Granada",                             subtitulo: 'Manuel Bayona presenta su libro',                                        fecha: '2026-02-27', hora: '', lugar: 'Atrio del Hotel Palacio Santa Paula',                        ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de Manuel Bayona en el Atrio del Hotel Palacio Santa Paula de Granada.' },
  { id: 'ev-052', tipo: 'Presentación',  titulo: "'Crónica de un profesor de instituto' en Salobreña",              subtitulo: 'Daniel Morales Escobar presenta su libro',                              fecha: '2026-02-27', hora: '', lugar: 'Salobreña',                                                 ciudad: 'Salobreña (Granada)',      imagen: '', descripcion: 'Presentación en Salobreña de la obra de Daniel Morales Escobar.' },
  { id: 'ev-053', tipo: 'Presentación',  titulo: "'Crónica de un profesor de instituto' en Granada",                subtitulo: 'Presentación del libro de Daniel Morales Escobar',                      fecha: '2026-02-20', hora: '', lugar: 'Granada',                                                   ciudad: 'Granada',                 imagen: '', descripcion: 'Presentación de Crónica de un profesor de instituto de Daniel Morales Escobar en Granada.' },
  { id: 'ev-054', tipo: 'Presentación',  titulo: "'Cómodamente adormecido' en el ciclo Letras Compartidas de Mijas", subtitulo: 'Juan Quero presenta su novela en Mijas',                               fecha: '2025-04-22', hora: '', lugar: 'Ciclo Letras Compartidas',                                  ciudad: 'Mijas (Málaga)',           imagen: '', descripcion: 'Presentación de Cómodamente adormecido de Juan Quero en el ciclo Letras Compartidas de Mijas.' },
  { id: 'ev-055', tipo: 'Presentación',  titulo: "'Cómodamente adormecido' en El Patio de Fuengirola",              subtitulo: 'Juan Quero presenta su novela',                                         fecha: '2025-04-22', hora: '', lugar: 'El Patio, Fuengirola TV',                                   ciudad: 'Fuengirola (Málaga)',      imagen: '', descripcion: 'Entrevista y presentación de Juan Quero en El Patio de Fuengirola TV.' },
  { id: 'ev-056', tipo: 'Presentación',  titulo: "'El jardín de Estocolmo' en Melilla",                             subtitulo: 'Antonio César Morón presenta su novela',                                fecha: '2023-06-14', hora: '', lugar: 'La Librería de Melilla',                                    ciudad: 'Melilla',                 imagen: '', descripcion: 'Presentación de El jardín de Estocolmo en La Librería de Melilla con reportaje en TV Melilla.' },
];

// ─────────────────────────────────────────────────────────────────────────────
// DATOS — Blog: Entrevistas + Noticias
// ─────────────────────────────────────────────────────────────────────────────
const BLOG_RAW = [
  // ── Entrevistas 2026 ──
  { id: 'static-1',  slug: 'manuel-bayona-en-letras-mixtas',                   titulo: 'Manuel Bayona en Letras Mixtas',                                              resumen: 'Francisco Quintero entrevista a Manuel Bayona sobre «La gestión del silencio», una obra que aborda la necesidad de recuperar la escucha y la humanización dentro de las organizaciones sanitarias.', autor: 'Manuel Bayona',              fecha: '2026-07-20', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/07/gestion-1024x576.jpg',                                                                                  tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/manuel-bayona-en-letras-mixtas/' },
  { id: 'static-2',  slug: 'entrevista-a-alejandro-santiago-en-educa-edtech-group', titulo: 'Alejandro Santiago en Educa EdTech Group',                                titulo: 'Alejandro Santiago en Educa EdTech Group',                                    resumen: 'El director de Editorial Nazarí habla sobre la evaluación de manuscritos, el equilibrio entre calidad literaria y viabilidad comercial, y el impacto responsable de la inteligencia artificial en el mundo editorial.', autor: 'Alejandro Santiago',        fecha: '2026-07-08', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/07/alejandro-santiago-en-educa-edtech-1024x576.jpg',                                                            tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/entrevista-a-alejandro-santiago-en-educa-edtech-group/' },
  { id: 'static-3',  slug: 'irene-bosch-blanco-en-temps-de-llibres',            titulo: 'Irene Bosch Blanco en Temps de Llibres',                                      resumen: 'Irene Bosch Blanco habla sobre su novela «Caminando con tus ojos» en el programa «Temps de Llibres», explorando los temas de superación y resiliencia que impulsan su narrativa.', autor: 'Irene Bosch Blanco',         fecha: '2026-07-08', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/07/temps-de-llibres-irene-bosch-blanco.jpg',                                                                   tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/irene-bosch-blanco-en-temps-de-llibres/' },
  { id: 'static-4',  slug: 'daniel-morales-en-radio-salobrena',                 titulo: 'Daniel Morales en Radio Salobreña',                                           resumen: 'Daniel Morales Escobar presenta en Radio Salobreña su libro «Crónica de un profesor de instituto», un recorrido casi cubista por décadas de enseñanza desde las aulas granadinas hasta la jubilación.', autor: 'Daniel Morales Escobar',     fecha: '2026-02-27', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/02/cronica-granada-01-1024x712.jpg',                                                                            tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/daniel-morales-en-radio-salobrena/' },
  { id: 'static-5',  slug: 'dulce-lopez-en-la-trinchera-de-los-libros',         titulo: 'Dulce López en «La trinchera de los libros»',                                 resumen: 'Dulce López habla de su carrera y su novela «Creo que te quiero» en este programa literario, explorando el silencio, el miedo, la soledad y el amor a través de sus protagonistas.', autor: 'Dulce López Rodríguez',      fecha: '2026-02-26', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/02/untitled-design.jpg',                                                                                        tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/dulce-lopez-en-la-trinchera-de-los-libros/' },
  { id: 'static-6',  slug: 'torcuato-romero-el-tablero-de-ajedrez',             titulo: 'Torcuato Romero y «El tablero de ajedrez» en El abanico de los lunes',       resumen: 'Conversación con Torcuato Romero sobre su trayectoria literaria y las claves de su novela «El tablero de ajedrez», que explora la fragilidad y la belleza a través de una relación médico-paciente.', autor: 'Torcuato Romero',            fecha: '2026-02-18', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/02/el-tablero-de-ajedrez-torcuato-romero-lopez-72ppp.jpg',                                                          tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/torcuato-romero-y-el-tablero-de-ajedrez-en-el-abanico-de-los-lunes/' },
  { id: 'static-7',  slug: 'dulce-lopez-cafes-literarios',                      titulo: 'Dulce López Rodríguez en Cafés literarios',                                   resumen: 'La autora dialoga con Álvaro García Conde en el pódcast «Cafés literarios» de la Universidad de Jaén sobre «Creo que te quiero», sus temas y su proceso creativo.', autor: 'Dulce López Rodríguez',      fecha: '2026-02-10', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/02/entrevista-dulce-lopez-1024x761.jpeg',                                                                         tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/dulce-lopez-rodriguez-y-creo-que-te-quiero-en-cafes-literarios/' },
  { id: 'static-8',  slug: 'manuel-bayona-medico-interactivo',                  titulo: 'Manuel Bayona en El Médico Interactivo',                                      resumen: 'Entrevista a Manuel Bayona sobre «La gestión del silencio», una obra que defiende la humanización sanitaria, la empatía y la comunicación ética como pilares del liderazgo en salud.', autor: 'Manuel Bayona',              fecha: '2026-02-04', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/02/manuel-bayona-entrevista-1024x683.jpg',                                                                         tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/manuel-bayona-y-la-gestion-del-silencio-en-el-medico-interactivo/' },
  { id: 'static-9',  slug: 'al-tercer-dia-podcast-mi-experiencia',              titulo: '«Al tercer día» en el pódcast «Mi experiencia como escritor»',               resumen: 'David Macías habla de su novela histórica «Al tercer día», donde un centurión romano documenta la ejecución de Jesús desde una perspectiva política y terrenal, cuestionando siglos de dogma.', autor: 'David Macías Gómez',         fecha: '2026-01-26', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/01/imagen_cabecera_al_tercer_dia.jpg',                                                                           tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/al-tercer-dia-en-el-podcast-mi-experiencia-como-escritor/' },
  // ── Entrevistas 2025 ──
  { id: 'static-10', slug: 'jesus-avila-granados-libros-y-libretos',            titulo: 'Jesús Ávila Granados en «Libros y libretos»',                                resumen: 'Paqui Sánchez Galbarro entrevista a Jesús Ávila Granados sobre «Espacios naturales con historia», una de las más de cien obras publicadas por este prolífico autor.', autor: 'Jesús Ávila Granados',       fecha: '2025-09-29', imagen_url: '', tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/jesus-avila-granados-en-libros-y-libretos/' },
  { id: 'static-11', slug: 'juan-de-dios-villanueva-roa-poeta-armada',          titulo: 'Juan de Dios Villanueva Roa en Poeta Armada',                                resumen: 'Grace Gálvez entrevista al poeta granadino sobre «Noviembre», poemario con quince poemas traducidos a varios idiomas y códigos QR para escuchar las versiones originales.', autor: 'Juan de Dios Villanueva Roa', fecha: '2025-07-31', imagen_url: '', tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/entrevista-a-juan-de-dios-villanueva-roa-en-poeta-armada/' },
  { id: 'static-12', slug: 'comodamente-adormecido-mijas-tv',                   titulo: '«Cómodamente adormecido» en Mijas TV',                                        resumen: 'Juan Quero presenta su novela «Cómodamente adormecido» en el ciclo literario de Mijas TV, una obra que invita a reflexionar sobre la comodidad y el conformismo contemporáneo.', autor: 'Juan Quero',                 fecha: '2025-04-22', imagen_url: '', tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/comodamente-adormecido-en-mijas-tv/' },
  { id: 'static-13', slug: 'comodamente-adormecido-fuengirola-tv',              titulo: '«Cómodamente adormecido» en Fuengirola TV',                                   resumen: 'Juan Quero habla de «Cómodamente adormecido» en el programa El Patio de Fuengirola TV, explorando los temas centrales de su novela.', autor: 'Juan Quero',                 fecha: '2025-04-22', imagen_url: '', tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/comodamente-adormecido-en-fuengirola-tv/' },
  { id: 'static-14', slug: 'cuando-termina-la-ciencia-la-voz-a-ti-debida',     titulo: '«Cuando termina la ciencia» en La voz a ti debida',                           resumen: 'Susana Collado presenta «Cuando termina la ciencia y empieza la ficción» en este programa cultural y literario, dialogando sobre la intersección entre ciencia y narrativa.', autor: 'Susana Collado',             fecha: '2025-02-06', imagen_url: '', tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/cuando-termina-la-ciencia-y-empieza-la-ficcion-en-la-voz-a-ti-debida/' },
  { id: 'static-15', slug: 'susana-collado-onda-cero-madrid-sur',               titulo: 'Susana Collado en Onda Cero Madrid Sur',                                      resumen: 'Susana Collado habla de su libro «Cuando termina la ciencia y empieza la ficción» en Onda Cero Madrid Sur, acercando la divulgación científica al gran público.', autor: 'Susana Collado',             fecha: '2025-01-23', imagen_url: '', tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/susana-collado-en-onda-cero-madrid-sur/' },
  { id: 'static-16', slug: 'jonas-y-la-esperanza-buenos-dias-albolote',         titulo: '«Jonás y la esperanza» en Buenos Días Albolote',                              resumen: 'Juan Carlos Rodríguez Torres presenta su novela «Jonás y la esperanza» en el programa local Buenos Días Albolote, hablando del proceso creativo y los temas de su obra.', autor: 'Juan Carlos Rodríguez Torres', fecha: '2025-01-13', imagen_url: '', tipo: 'entrevista', url_externa: 'https://www.editorialnazari.com/jonas-y-la-esperanza-en-buenos-dias-albolote/' },
  // ── Noticias 2026 ──
  { id: 'noticia-1',  slug: 'destilacion-en-ribadavia',                          titulo: '«Destilación» en Ribadavia',                                                  resumen: 'Paula R. Bouzas presenta «Destilación» en el Museo Etnológico de Ribadavia, con introducción de José Luis Chao. Una velada poética en el corazón de la Ribeira Sacra.', autor: 'Editorial Nazarí',           fecha: '2026-08-24', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/08/destilacion-ribadavia-01.jpg',                                                                              tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/destilacion-en-ribadavia/' },
  { id: 'noticia-2',  slug: 'el-mundial-que-espana-no-gano-en-torrelavega',      titulo: '«El mundial que España no ganó» en Torrelavega',                              resumen: 'Javier Ruiz Barquín presenta su libro en la librería Dlibros de Torrelavega, en una charla con el escritor Marcos Pereda sobre fútbol, historia y literatura.', autor: 'Editorial Nazarí',           fecha: '2026-08-24', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/08/el-mundial-torrelavega-01-1024x683.jpg',                                                                        tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/el-mundial-que-espana-no-gano-en-torrelavega/' },
  { id: 'noticia-3',  slug: 'presentacion-gestion-del-silencio-madrid',          titulo: 'Así fue la presentación de «La gestión del silencio» en Madrid',              resumen: 'Manuel Bayona presentó su libro en Redacción Médica ante profesionales sanitarios que debatieron sobre liderazgo, organizaciones y la humanización de la medicina.', autor: 'Editorial Nazarí',           fecha: '2026-07-08', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/07/manuel-bayona-en-redaccion-medica-1024x576.jpg',                                                               tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-la-gestion-del-silencio-en-madrid/' },
  { id: 'noticia-4',  slug: 'caminando-con-tus-ojos-en-atarfe',                  titulo: '«Caminando con tus ojos» en Atarfe',                                          resumen: 'Irene Bosch Blanco presenta su ópera prima en el Centro Cultural Medina Elvira de Atarfe, con una emotiva velada literaria llena de superación y resiliencia.', autor: 'Editorial Nazarí',           fecha: '2026-06-05', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/06/2026-05-27-caminando-con-tus-ojos-atarfe-01-1024x768.jpg',                                                         tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/caminando-con-tus-ojos-en-atarfe/' },
  { id: 'noticia-5',  slug: 'habitacion-320-barcelona-2',                        titulo: '2ª presentación de «La habitación 320» en el Café de la Ópera de Barcelona', resumen: 'El Grupo Bojador agotó el aforo y recibió a asistentes de pie en su segunda presentación en el emblemático Café de la Ópera de Barcelona.', autor: 'Editorial Nazarí',           fecha: '2026-06-05', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-2a-presentacion-de-la-habitacion-320-en-el-cafe-de-la-opera-de-barcelona/' },
  { id: 'noticia-6',  slug: 'manuel-bayona-el-comercio',                          titulo: 'Manuel Bayona en «El Comercio»',                                              resumen: 'El diario El Comercio de Gijón recoge la presentación de «La gestión del silencio» y la trayectoria de Manuel Bayona como médico y experto en gestión sanitaria.', autor: 'Editorial Nazarí',           fecha: '2026-06-03', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/06/2026-05-29-el-comercio-1024x682.jpg',                                                                              tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/manuel-bayona-en-el-comercio/' },
  { id: 'noticia-7',  slug: 'nostalgias-en-madrid',                               titulo: 'Así fue la presentación de «Nostalgias» en Madrid',                           resumen: 'Susana Collado Vázquez presentó «Nostalgias» en la Biblioteca Eugenio Trías dentro del ciclo Médicos escritores, ante un público entregado y numeroso.', autor: 'Editorial Nazarí',           fecha: '2026-05-27', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/nostalgias-en-la-eugenio-trias/' },
  { id: 'noticia-8',  slug: 'rios-nunca-miran-atras-alcira',                      titulo: 'Así fue la presentación de «Los ríos nunca miran atrás» en Alzira',           resumen: 'José Luis Monroy Antón presentó su thriller rural en la Biblioteca Municipal de Alzira, destacando la profundidad de los personajes y la ambientación del paisaje valenciano.', autor: 'Editorial Nazarí',           fecha: '2026-05-19', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-los-rios-nunca-miran-atras-en-alcira/' },
  { id: 'noticia-9',  slug: 'intramuros-sevilla',                                  titulo: 'Así fue la presentación de «Intramuros» en Sevilla',                          resumen: 'José Piñero Mira presentó su colección de relatos en la Sala Griot de Sevilla, recorriendo las catorce ciudades europeas que dan vida a sus trece cuentos.', autor: 'Editorial Nazarí',           fecha: '2026-05-18', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-intramuros-en-sevilla/' },
  { id: 'noticia-10', slug: 'escribir-en-granada-tomas-moreno',                   titulo: '«Escribir en Granada», por Tomás Moreno',                                     resumen: 'Carta al Director publicada en el diario Ideal reflexionando sobre la creación literaria, el reconocimiento cultural y el talento de los autores andaluces.', autor: 'Tomás Moreno',              fecha: '2026-05-15', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/05/escribir-en-granada-1024x1024.jpg',                                                                              tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/escribir-en-granada-por-tomas-moreno/' },
  { id: 'noticia-11', slug: 'feria-del-libro-granada-2026',                       titulo: 'Así fue la Feria del Libro de Granada «Así que pasen cinco años»',            resumen: 'Crónica de la 44.ª Feria del Libro de Granada bajo el lema lorquiano, con reflexiones sobre el ambiente literario y la literatura que perdura.', autor: 'Editorial Nazarí',           fecha: '2026-05-12', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-feria-del-libro-de-granada-asi-que-pasen-cinco-anos/' },
  { id: 'noticia-12', slug: 'victoria-eugenia-munoz-sagrada-familia',             titulo: 'Victoria Eugenia Muñoz con alumnos del Colegio Sagrada Familia de Granada',  resumen: 'La autora compartió su experiencia literaria con estudiantes de 1.º y 2.º de ESO, acercando la lectura y la escritura creativa a los más jóvenes.', autor: 'Editorial Nazarí',           fecha: '2026-05-12', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-el-encuentro-de-victoria-eugenia-munoz-con-los-alumnos-del-colegio-sagrada-familia-de-granada/' },
  { id: 'noticia-13', slug: 'maneras-de-estar-tumbada-murcia',                    titulo: 'Así fue la presentación de «Maneras de estar tumbada» en Murcia',             resumen: 'Mar Navarro G. presentó su novela en la Biblioteca Regional de Murcia, en una tarde literaria que reunió a numerosos lectores entusiastas.', autor: 'Editorial Nazarí',           fecha: '2026-05-11', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-maneras-de-estar-tumbada-en-murcia/' },
  { id: 'noticia-14', slug: 'torcuato-romero-ies-christine-picasso',              titulo: 'Torcuato Romero con el club de lectura del IES Christine Picasso de Málaga',  resumen: 'Encuentro del Día del Libro con el autor de «El tablero de ajedrez» y los alumnos del club de lectura, debatiendo sobre literatura y el proceso de escritura.', autor: 'Editorial Nazarí',           fecha: '2026-05-11', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-el-encuentro-de-torcuato-romero-lopez-con-el-club-de-lectura-del-ies-christine-picasso-de-malaga/' },
  { id: 'noticia-15', slug: 'habitacion-320-barcelona',                            titulo: '«La habitación 320» en el Café de la Ópera de Barcelona',                    resumen: 'El Grupo Bojador presentó su colección de relatos ante un aforo completo y asistentes de pie en el histórico Café de la Ópera de La Rambla de Barcelona.', autor: 'Editorial Nazarí',           fecha: '2026-05-11', imagen_url: 'https://www.editorialnazari.com/wp-content/uploads/2026/05/cafe-de-la-opers-26.04.jpg',                                                                                    tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-la-habitacion-320-en-el-cafe-de-la-opera-de-barcelona/' },
  { id: 'noticia-16', slug: 'habitacion-320-sant-jordi',                           titulo: '«La habitación 320» en Sant Jordi',                                           resumen: 'Celebración doble de la fiesta del libro y presentación de La habitación 320 del Grupo Bojador en Barcelona y Gavà.', autor: 'Editorial Nazarí',           fecha: '2026-05-11', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-el-lanzamiento-de-la-habitacion-320-en-sant-jordi/' },
  { id: 'noticia-17', slug: 'preludio-muerte-fuga-almeria',                        titulo: 'Firma de «Preludio, muerte y fuga» en la Feria del Libro de Almería',         resumen: 'Firma de ejemplares de la quinta obra de Arturo Palenzuela Reyes en la 46.ª edición de la Feria del Libro de Almería.', autor: 'Editorial Nazarí',           fecha: '2026-05-07', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-firma-de-preludio-muerte-y-fuga-en-la-feria-del-libro-de-almeria/' },
  { id: 'noticia-18', slug: 'caminando-con-tus-ojos-ciutadella',                   titulo: '«Caminando con tus ojos» en La Ciutadella',                                   resumen: 'Irene Bosch presentó su novela en la antigua farmacia Llabrés de la Ciutadella el 17 de abril.', autor: 'Editorial Nazarí',           fecha: '2026-05-07', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-caminando-con-tus-ojos-en-la-ciutadella/' },
  { id: 'noticia-19', slug: 'caminando-con-tus-ojos-es-migjorn',                   titulo: '«Caminando con tus ojos» en Es Migjorn Gran',                                 resumen: 'El Club de jubilados de Es Migjorn Gran recibió a Irene Bosch el 15 de abril para presentar su libro.', autor: 'Editorial Nazarí',           fecha: '2026-05-07', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-caminando-con-tus-ojos-en-es-migjorn-gran/' },
  { id: 'noticia-20', slug: 'caminando-con-tus-ojos-ferrerias',                    titulo: '«Caminando con tus ojos» en Ferrerías',                                       resumen: 'Irene Bosch Blanco presentó su novela en la Biblioteca de Ferrerías el 16 de abril, acompañada de María del Mar Ocaña.', autor: 'Editorial Nazarí',           fecha: '2026-05-07', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-caminando-con-tus-ojos-en-ferrerias/' },
  { id: 'noticia-21', slug: 'las-doce-cosechas-ceuta',                             titulo: '«Las doce cosechas» en Ceuta',                                                resumen: 'Presentación de la novela de Maite Cuesta el 15 de abril en la Biblioteca Pública del Estado en Ceuta.', autor: 'Editorial Nazarí',           fecha: '2026-04-23', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-las-doce-cosechas-en-ceuta/' },
  { id: 'noticia-22', slug: 'caminando-con-tus-ojos-ceip-pere-casasnovas',         titulo: '«Caminando con tus ojos» en el CEIP Pere Casasnovas de Ciutadella',            resumen: 'Irene Bosch Blanco realizó un taller para alumnos de sexto de primaria el 14 de abril en un centro con alumnado de diversidad funcional.', autor: 'Editorial Nazarí',           fecha: '2026-04-22', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-caminando-con-tus-ojos-en-el-ceip-pere-casasnovas-de-ciutadella/' },
  { id: 'noticia-23', slug: 'letras-celestes-antigona-marquez',                    titulo: 'VII Encuentro Letras Celestes con Antígona Márquez Pascual',                  resumen: 'Antígona Márquez impartió charla sobre la literatura de viajes del escocés Robert Dundas Murray en La Puebla de los Infantes.', autor: 'Editorial Nazarí',           fecha: '2026-04-16', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-el-vii-encuentro-letras-celestes-con-antigona-marquez-pascual/' },
  { id: 'noticia-24', slug: 'los-rios-nunca-miran-atras-granada',                  titulo: '«Los ríos nunca miran atrás» en Granada',                                     resumen: 'Presentación de la novela de José Luis Monroy Antón en el Cuarto Real de Santo Domingo.', autor: 'Editorial Nazarí',           fecha: '2026-04-15', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-los-rios-nunca-miran-atras-en-granada/' },
  { id: 'noticia-25', slug: 'tu-y-el-amor-orihuela',                               titulo: '«Tú y el amor» en Orihuela',                                                  resumen: 'Presentación del poemario de Jesús Paredes Ortiz en la Biblioteca Pública Municipal María Moliner de Orihuela.', autor: 'Editorial Nazarí',           fecha: '2026-04-13', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-tu-y-el-amor-en-orihuela/' },
  { id: 'noticia-26', slug: 'recital-enrique-moron-granada',                       titulo: 'Recital de Enrique Morón en Granada',                                         resumen: 'Recital de poesía el 25 de marzo en el Centro Artístico Literario y Científico de Granada por publicación digital de su Poesía completa.', autor: 'Editorial Nazarí',           fecha: '2026-04-10', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-el-recital-de-enrique-moron-en-granada/' },
  { id: 'noticia-27', slug: 'lagrimaciendo-sobre-el-vacio-illora',                 titulo: '«Lagrimaciendo sobre el vacío» en Íllora',                                    resumen: 'Presentación del poemario de Ana Barea Arco en la Biblioteca Pública Municipal de Íllora.', autor: 'Editorial Nazarí',           fecha: '2026-04-10', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-lagrimaciendo-sobre-el-vacio-en-illora/' },
  { id: 'noticia-28', slug: 'el-canto-triste-del-cuervo-granada',                  titulo: '«El canto triste del cuervo» en Granada',                                     resumen: 'Presentación de la novela histórica de José Prados Osuna en la Biblioteca de Andalucía.', autor: 'Editorial Nazarí',           fecha: '2026-04-10', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-el-canto-triste-del-cuervo-en-granada/' },
  { id: 'noticia-29', slug: 'la-gestion-del-silencio-malaga',                      titulo: '«La gestión del silencio» en Málaga',                                         resumen: 'Presentación del libro de Manuel Bayona el 26 de marzo con profesionales sanitarios en el Colegio Oficial de Médicos de Málaga.', autor: 'Editorial Nazarí',           fecha: '2026-04-10', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-la-gestion-del-silencio-en-malaga/' },
  { id: 'noticia-30', slug: 'cronica-profesor-en-ideal',                            titulo: '«Crónica de un profesor de instituto» en Ideal',                              resumen: 'Novela de Daniel Morales Escobar aparece en Ideal con artículo de Antonio Arenas.', autor: 'Editorial Nazarí',           fecha: '2026-04-06', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/cronica-de-un-profesor-de-instituto-en-ideal/' },
  { id: 'noticia-31', slug: 'dia-poesia-canal-sur',                                 titulo: 'Día de la Poesía en Canal Sur',                                               resumen: 'Celebración del Día Mundial de la Poesía el 21 de marzo en el Centro Federico García Lorca con cobertura mediática.', autor: 'Editorial Nazarí',           fecha: '2026-03-29', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/dia-de-la-poesia-en-canal-sur/' },
  { id: 'noticia-32', slug: 'destilacion-carmen-victoria',                          titulo: '«Destilación» en el Carmen de la Victoria (Granada)',                         resumen: 'Presentación en un espacio íntimo de Granada destacando la voz de Paula R. Bouzas de Ribadavia.', autor: 'Editorial Nazarí',           fecha: '2026-03-27', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-destilacion-en-el-carmen-de-la-victoria/' },
  { id: 'noticia-33', slug: 'la-vieja-inquietud-del-aire-cordoba',                  titulo: '«La vieja inquietud del aire» en Córdoba',                                    resumen: 'Presentación del libro de Diego Castillo Barco en la Biblioteca Pública Grupo Cántico de Córdoba el 21 de marzo.', autor: 'Editorial Nazarí',           fecha: '2026-03-26', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-la-vieja-inquietud-del-aire-en-cordoba/' },
  { id: 'noticia-34', slug: 'la-gestion-del-silencio-huelma',                       titulo: '«La gestión del silencio» en Huelma',                                         resumen: 'Evento del 20 de marzo presentando la obra de Manuel Bayona García, considerada uno de los destacados culturales del municipio.', autor: 'Editorial Nazarí',           fecha: '2026-03-26', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-la-gestion-del-silencio-en-huelma/' },
  { id: 'noticia-35', slug: 'las-doce-cosechas-granada',                            titulo: '«Las doce cosechas» en Granada',                                              resumen: 'Presentación de la nueva novela de Maite Cuesta en la Biblioteca Pública Municipal Francisco Ayala.', autor: 'Editorial Nazarí',           fecha: '2026-03-25', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-las-doce-cosechas-en-granada/' },
  { id: 'noticia-36', slug: 'los-rios-nunca-miran-atras-jerte',                     titulo: '«Los ríos nunca miran atrás» en Jerte',                                       resumen: 'Presentación de la obra de José Luis Monroy Antón en el Festival Literario Despierta 26, dedicado a la novela negra.', autor: 'Editorial Nazarí',           fecha: '2026-03-25', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-los-rios-nunca-miran-atras-en-jerte/' },
  { id: 'noticia-37', slug: 'caminando-con-tus-ojos-once',                          titulo: '«Caminando con tus ojos» en la ONCE',                                         resumen: 'Irene Bosch Blanco presentó su libro el 19 de marzo en la sede de la ONCE en Granada, acompañada de Sandra Rodríguez Jiménez.', autor: 'Editorial Nazarí',           fecha: '2026-03-25', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-caminando-con-tus-ojos-en-la-once/' },
  { id: 'noticia-38', slug: 'sierra-de-irta-avila-granados',                        titulo: '«La Sierra de Irta, paraíso templario», por Jesús Ávila Granados',            resumen: 'Artículo que invita a recorrer la Sierra de Irta, un enclave con historia, paisaje y memoria templaria.', autor: 'Jesús Ávila Granados',       fecha: '2026-03-18', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/la-sierra-de-irta-paraiso-templario-por-jesus-avila-granados/' },
  { id: 'noticia-39', slug: 'caminando-con-tus-ojos-cocina-molinos',                titulo: '«Caminando con tus ojos» en La Cocina de Molinos',                            resumen: 'Presentación del 12 de marzo en el corazón de Granada ante un público con conocimiento personal de la discapacidad.', autor: 'Editorial Nazarí',           fecha: '2026-03-16', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-caminando-con-tus-ojos-en-la-cocina-de-molinos/' },
  { id: 'noticia-40', slug: 'caminando-con-tus-ojos-ceip-la-inmaculada',            titulo: '«Caminando con tus ojos» en el CEIP La Inmaculada',                           resumen: 'Encuentro especial del 9 de marzo entre Irene Bosch y alumnos del colegio para presentar su novela.', autor: 'Editorial Nazarí',           fecha: '2026-03-12', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-caminando-con-tus-ojos-en-el-ceip-ecoescuela-la-inmaculada/' },
  { id: 'noticia-41', slug: 'huyendo-granada-dia-mujer',                             titulo: '«Huyendo a Granada» y el Día Internacional de la Mujer',                      resumen: 'El club de lectura de la Biblioteca Municipal de La Chana se adentró en la obra de Victoria Eugenia Muñoz el 8 de marzo.', autor: 'Editorial Nazarí',           fecha: '2026-03-12', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/huyendo-a-granada-y-el-dia-internacional-de-la-mujer/' },
  { id: 'noticia-42', slug: 'mesa-redonda-tienes-tiempo-albolote',                   titulo: 'Mesa redonda «¿Tienes tiempo para ti? Escribe» en Albolote',                  resumen: 'Mesa redonda el 6 de marzo en Albolote reuniendo varias poetas para reflexionar sobre creación en la vida cotidiana.', autor: 'Editorial Nazarí',           fecha: '2026-03-09', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-mesa-redonda-tienes-tiempo-para-ti-escribe-en-albolote/' },
  { id: 'noticia-43', slug: 'huyendo-granada-mujer-al-andalus',                      titulo: '«Huyendo a Granada» y la mujer en al-Ándalus',                                resumen: 'Evento del 6 de marzo en Montejícar explorando la vida cotidiana femenina en al-Ándalus a través de la novela.', autor: 'Editorial Nazarí',           fecha: '2026-03-09', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/huyendo-a-granada-y-la-mujer-en-al-andalus/' },
  { id: 'noticia-44', slug: 'huyendo-granada-temporada-literatura',                  titulo: '«Huyendo a Granada» reinicia su temporada de literatura',                     resumen: 'Club de lectura del Colegio La Presentación recorrió callejuelas y monumentos de Granada con Victoria Eugenia Muñoz.', autor: 'Editorial Nazarí',           fecha: '2026-03-03', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/huyendo-a-granada-reinicia-su-temporada-de-literatura/' },
  { id: 'noticia-45', slug: 'cronica-profesor-salobrena',                            titulo: '«Crónica de un profesor de instituto» en Salobreña',                           resumen: 'Presentación en Salobreña de la obra de Daniel Morales Escobar.', autor: 'Editorial Nazarí',           fecha: '2026-02-27', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-cronica-de-un-profesor-de-instituto-en-salobrena/' },
  { id: 'noticia-46', slug: 'la-gestion-del-silencio-granada',                       titulo: '«La gestión del silencio» en Granada',                                        resumen: 'Presentación de Manuel Bayona en el Atrio del Hotel Palacio Santa Paula de Granada.', autor: 'Editorial Nazarí',           fecha: '2026-02-27', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-la-gestion-del-silencio-en-granada/' },
  { id: 'noticia-47', slug: 'cronica-profesor-instituto-presentacion',               titulo: 'Presentación de «Crónica de un profesor de instituto»',                       resumen: 'Presentación de la obra de Daniel Morales Escobar sobre décadas de enseñanza en Granada.', autor: 'Editorial Nazarí',           fecha: '2026-02-20', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/asi-fue-la-presentacion-de-cronica-de-un-profesor-de-instituto/' },
  { id: 'noticia-48', slug: 'caminando-con-tus-ojos-cafe-literario-atarfe',          titulo: '«Caminando con tus ojos» en el Café Literario de Atarfe',                     resumen: 'Encuentro con autores el 22 de abril durante la semana del libro en Atarfe.', autor: 'Editorial Nazarí',           fecha: '2026-06-05', imagen_url: '', tipo: 'noticia',    url_externa: 'https://www.editorialnazari.com/caminando-con-tus-ojos-en-el-cafe-literario-de-atarfe/' },
];

// ─────────────────────────────────────────────────────────────────────────────
// IMPORT
// ─────────────────────────────────────────────────────────────────────────────
async function main() {
  console.log('🚀 Iniciando importación de datos Nazarí a Firestore...\n');

  // ── Eventos ──────────────────────────────────────────────────────────────
  const eventoDocs = EVENTOS_RAW.map(ev => {
    const fecha = parseFecha(ev.fecha);
    const tipo  = tipoEventoLabel(ev.tipo);
    const doc = {
      titulo:      ev.titulo,
      subtitulo:   ev.subtitulo || '',
      descripcion: ev.descripcion || '',
      fecha:       admin.firestore.Timestamp.fromDate(fecha),
      lugar:       ev.lugar || '',
      ciudad:      ev.ciudad || '',
      tipo:        tipo,
      activo:      true,
      eliminado:   false,
      _importado:  true,
      _fuente:     'eventos-data.js',
    };
    if (ev.hora)          doc.hora         = ev.hora;
    if (ev.imagen)        { doc.imagen_url = ev.imagen; doc.imagen = ev.imagen; }
    if (ev.autor_nombre)  doc.autor_nombre = ev.autor_nombre;
    return [ev.id, doc];
  });

  await uploadBatch(colBase.collection('eventos'), eventoDocs, 'Eventos');

  // ── Blog (Entrevistas + Noticias) ─────────────────────────────────────────
  const blogDocs = BLOG_RAW.map(p => {
    const fecha = parseFecha(p.fecha);
    const doc = {
      titulo:            p.titulo,
      slug:              p.slug,
      resumen:           p.resumen || '',
      contenido:         '',
      autor:             p.autor || '',
      categoria_id:      p.tipo === 'entrevista' ? 'Entrevistas' : 'Noticias',
      tipo:              p.tipo,  // 'entrevista' | 'noticia'
      estado:            'publicado',
      publicada:         true,
      fecha_publicacion: admin.firestore.Timestamp.fromDate(fecha),
      etiquetas:         [],
      imagenes:          [],
      destacado:         false,
      visitas:           0,
      eliminado:         false,
      seo:               { meta_title: '', meta_description: '', keywords: [] },
      _importado:        true,
      _fuente:           'blog.html',
    };
    if (p.imagen_url)    doc.imagen_url  = p.imagen_url;
    if (p.url_externa)   doc.url_externa = p.url_externa;
    return [p.id, doc];
  });

  await uploadBatch(colBase.collection('blog'), blogDocs, 'Blog (noticias + entrevistas)');

  console.log('\n✅ Importación completada.');
  console.log(`   ${EVENTOS_RAW.length} eventos  →  empresas/${EID}/eventos`);
  console.log(`   ${BLOG_RAW.length} entradas  →  empresas/${EID}/blog`);
  console.log('\nLos datos ya son visibles en el módulo web de la app Flutter y en la web de Nazarí.');
  process.exit(0);
}

main().catch(err => {
  console.error('❌ Error en la importación:', err.message || err);
  process.exit(1);
});
