// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVK8AUerxlYcr6N1fZg6t0RL8c7ajfNzU',
    appId: '1:1085482191658:web:c5461353b123ab92d62c53',
    messagingSenderId: '1085482191658',
    projectId: 'planeaapp-4bea4',
    authDomain: 'planeaapp-4bea4.firebaseapp.com',
    storageBucket: 'planeaapp-4bea4.firebasestorage.app',
    measurementId: 'G-D71JMGGGZM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvOaB1hF_sF-A6jMZ0MusttuhzSMDezb4',
    appId: '1:1085482191658:android:c2de28caf383e9e4d62c53',
    messagingSenderId: '1085482191658',
    projectId: 'planeaapp-4bea4',
    storageBucket: 'planeaapp-4bea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG-et3c61Wq-zKlUD-mI_Kaor9dBw7ORg',
    appId: '1:1085482191658:ios:580c2ff49b326bb1d62c53',
    messagingSenderId: '1085482191658',
    projectId: 'planeaapp-4bea4',
    storageBucket: 'planeaapp-4bea4.firebasestorage.app',
    iosBundleId: 'com.example.planeagFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG-et3c61Wq-zKlUD-mI_Kaor9dBw7ORg',
    appId: '1:1085482191658:ios:580c2ff49b326bb1d62c53',
    messagingSenderId: '1085482191658',
    projectId: 'planeaapp-4bea4',
    storageBucket: 'planeaapp-4bea4.firebasestorage.app',
    iosBundleId: 'com.example.planeagFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6lg_F_2BrtLZZX9acEvzAQOWrJDYmMxI',
    appId: '1:1085482191658:web:00209c643c77226bd62c53',
    messagingSenderId: '1085482191658',
    projectId: 'planeaapp-4bea4',
    authDomain: 'planeaapp-4bea4.firebaseapp.com',
    storageBucket: 'planeaapp-4bea4.firebasestorage.app',
    measurementId: 'G-X9D074WLRF',
  );
}
